### ISSUE TITLE
npx create-nullstack-app without name is throwing an error:

### ISSUE THREAD

**Issue by Mortaro** [nullstack/create-nullstack-app#8]
npx create-nullstack-app without name is currently throwing an error:

```
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:375:7)
    at Object.<anonymous> (C:\Repositories\create-nullstack-app\index.js:7:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Ideally it would ask the user the project name instead.

The following formats should be accepted as answer:
- `Project Name`
- `project-name`
- `projectName`
- `ProjectName`

However the question should suggest the first format so the user don't spend time thinking about it

**Comment by GuiDevloper** [comment]
Then, as usual, this one can be manually closed 😅

**Comment by Mortaro** [comment]
Thanks 💖 one day ill learn how to use the "closes" but it's not today 💩
